<a href="https://colab.research.google.com/github/VyshnaviKarpuram/word-prediction/blob/main/word%20prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
a=tf.constant('hello world')
print(a.numpy())

b'hello world'


In [ ]:
print(a)

tf.Tensor(b'hello world', shape=(), dtype=string)


In [ ]:
#b=tf.Session()
#print(b.run(a))
#b.close

In [ ]:
#scalar constant
a=tf.constant(42)
b=tf.constant(3.23)
c=tf.constant("hi hello")
print(a)
print(a.numpy())
print(b)
print(b.numpy())
print(c)
print(c.numpy())

tf.Tensor(42, shape=(), dtype=int32)
42
tf.Tensor(3.23, shape=(), dtype=float32)
3.23
tf.Tensor(b'hi hello', shape=(), dtype=string)
b'hi hello'


In [ ]:
#vector contant
a=tf.constant([1,2,3,4])
b=tf.constant([1.0,2.0,3.0])
print(a)
print(a.numpy())
print(b)
print(b.numpy())

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
[1 2 3 4]
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
[1. 2. 3.]


In [ ]:
#matrix constant
a=tf.constant([[1,2],[3,4]])
b=tf.constant([[1.1,2.2],[3.3,4.4]])
print(a)
print(a.numpy())
print(b)
print(b.numpy())

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
[[1 2]
 [3 4]]
tf.Tensor(
[[1.1 2.2]
 [3.3 4.4]], shape=(2, 2), dtype=float32)
[[1.1 2.2]
 [3.3 4.4]]


In [ ]:
#higher dimensional tensor constant
a=tf.constant([[[1,2,3],[1,2,3]],[[1,3,2],[4,2,6]]])
print(a)
print(a.numpy())

tf.Tensor(
[[[1 2 3]
  [1 2 3]]

 [[1 3 2]
  [4 2 6]]], shape=(2, 2, 3), dtype=int32)
[[[1 2 3]
  [1 2 3]]

 [[1 3 2]
  [4 2 6]]]


In [ ]:
#boolean constant
a=tf.constant(True)
print(a)
print(a.numpy())

tf.Tensor(True, shape=(), dtype=bool)
True


In [ ]:
#special constant
a=tf.zeros(shape=(2,2))
b=tf.ones(shape=(3,3))
print(a)
print(a.numpy())
print(b)
print(b.numpy())

tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)
[[0. 0.]
 [0. 0.]]
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
a=tf.constant(5.0)
b=tf.constant(3.0)
c=tf.multiply(a,b)
result=a*b
print(result)
print(result.numpy())
print(c.numpy())

tf.Tensor(15.0, shape=(), dtype=float32)
15.0
15.0


In [ ]:
a=tf.constant([1,2])
x=tf.constant([[1,2],[3,4],[5,6]])
y=tf.ones(x.shape[0])
print(x.get_shape())
print(y.get_shape())
print(a.get_shape())

(3, 2)
(3,)
(2,)


In [ ]:
a=tf.constant(1.52)
print(a)
print(a.numpy())
b=tf.cast(a,dtype=tf.int32)
print(b)
print(b.numpy())

tf.Tensor(1.52, shape=(), dtype=float32)
1.52
tf.Tensor(1, shape=(), dtype=int32)
1


In [ ]:
a=tf.constant(3.4)
b=tf.constant([[1,2],[3,4],[5,6]])
c=tf.constant([[1,2],[3,4],[5,6]])
print(tf.sqrt(a).numpy())
print(tf.add(b,c).numpy())
print(tf.multiply(b,c).numpy())

1.8439089
[[ 2  4]
 [ 6  8]
 [10 12]]
[[ 1  4]
 [ 9 16]
 [25 36]]


In [ ]:
x=tf.constant([[1.,2.,3.],[4.,5.,6.]])
print(x)
print(x.numpy())
print(x.shape)
print(x.dtype)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
<dtype: 'float32'>


In [ ]:
c=x+x
print(c.numpy())
d=5*x
print(d.numpy())
e=tf.transpose(x)
print(e.numpy())
r=tf.reduce_sum(x)
print(r.numpy())

[[ 2.  4.  6.]
 [ 8. 10. 12.]]
[[ 5. 10. 15.]
 [20. 25. 30.]]
[[1. 4.]
 [2. 5.]
 [3. 6.]]
21.0


In [ ]:
j=x@tf.transpose(x)
print(j.numpy())
f=tf.concat([x,x,x],axis=0)
print(f.numpy())

[[14. 32.]
 [32. 77.]]
<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(6, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [1., 2., 3.],
       [4., 5., 6.],
       [1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>>


In [ ]:
a=tf.constant([[1,2],[3,4]])
b=tf.constant([[1,2],[3,4]])
print(a*b.numpy())
print(tf.multiply(a,b).numpy())
print(a@b.numpy())

tf.Tensor(
[[ 1  4]
 [ 9 16]], shape=(2, 2), dtype=int32)
[[ 1  4]
 [ 9 16]]
tf.Tensor(
[[ 7 10]
 [15 22]], shape=(2, 2), dtype=int32)


In [ ]:
a=tf.nn.softmax(x,axis=-1)
print(a.numpy())

[[0.09003057 0.24472848 0.66524094]
 [0.09003057 0.24472848 0.66524094]]


In [ ]:
x=tf.constant([[1.0,2.0,3.0]])
logits=tf.constant([1.0,2.0,3.0])
softmax_probs=tf.nn.softmax(logits,axis=-1)
print(softmax_probs)

tf.Tensor([0.09003057 0.24472848 0.66524094], shape=(3,), dtype=float32)


**FASTAI**

In [ ]:
from fastai.vision.all import *

In [ ]:
path=untar_data(URLs.MNIST_SAMPLE)

## **RNN**

## **TASK-1**

In [ ]:
import numpy as np
from keras.models import Sequential
from keras.layers import SimpleRNN, Dense, Embedding
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.utils import to_categorical


# Generating some example sequential data
sentences = ['I love learning','I love python programming','I hate you',
             'Recurrent Neural Networks are powerful']

# Tokenizing the words
tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)
total_words = len(tokenizer.word_index) + 1

# Creating input sequences and their corresponding next words
input_sequences = []
for sentence in sentences:
    tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]
    for i in range(1, len(tokenized_sentence)):
        n_gram_sequence = tokenized_sentence[:i+1]
        input_sequences.append(n_gram_sequence)

# Padding sequences for consistent input size
max_sequence_length = max([len(seq) for seq in input_sequences])
input_sequences = pad_sequences(input_sequences, maxlen=max_sequence_length, padding='pre')

# Creating input and output data
X, y = input_sequences[:, :-1], input_sequences[:, -1]
y = to_categorical(y, num_classes=total_words)

# Building a simple RNN model
model = Sequential()
model.add(Embedding(input_dim=total_words, output_dim=50, input_length=max_sequence_length-1))
model.add(SimpleRNN(100, return_sequences=True))
model.add(SimpleRNN(100))
model.add(Dense(total_words, activation='softmax'))

# Compiling the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Training the model
model.fit(X, y, epochs=50, verbose=2)




Epoch 1/50
1/1 - 3s - loss: 2.5737 - accuracy: 0.0909 - 3s/epoch - 3s/step
Epoch 2/50
1/1 - 0s - loss: 2.4823 - accuracy: 0.1818 - 17ms/epoch - 17ms/step
Epoch 3/50
1/1 - 0s - loss: 2.3941 - accuracy: 0.3636 - 13ms/epoch - 13ms/step
Epoch 4/50
1/1 - 0s - loss: 2.3064 - accuracy: 0.3636 - 12ms/epoch - 12ms/step
Epoch 5/50
1/1 - 0s - loss: 2.2176 - accuracy: 0.3636 - 12ms/epoch - 12ms/step
Epoch 6/50
1/1 - 0s - loss: 2.1280 - accuracy: 0.3636 - 12ms/epoch - 12ms/step
Epoch 7/50
1/1 - 0s - loss: 2.0387 - accuracy: 0.3636 - 12ms/epoch - 12ms/step
Epoch 8/50
1/1 - 0s - loss: 1.9513 - accuracy: 0.3636 - 14ms/epoch - 14ms/step
Epoch 9/50
1/1 - 0s - loss: 1.8658 - accuracy: 0.4545 - 16ms/epoch - 16ms/step
Epoch 10/50
1/1 - 0s - loss: 1.7807 - accuracy: 0.4545 - 15ms/epoch - 15ms/step
Epoch 11/50
1/1 - 0s - loss: 1.6953 - accuracy: 0.4545 - 13ms/epoch - 13ms/step
Epoch 12/50
1/1 - 0s - loss: 1.6118 - accuracy: 0.4545 - 15ms/epoch - 15ms/step
Epoch 13/50
1/1 - 0s - loss: 1.5337 - accuracy: 0.454

In [ ]:
# Generating text using the trained model
seed_text = "Recurrent neural network"
next_words = 3
for _ in range(next_words):
    tokenized_seed = tokenizer.texts_to_sequences([seed_text])[0]
    tokenized_seed = pad_sequences([tokenized_seed], maxlen=max_sequence_length-1, padding='pre')
    predicted_word_index = np.argmax(model.predict(tokenized_seed), axis=-1)
    predicted_word = tokenizer.index_word[predicted_word_index[0]]
    seed_text += " " + predicted_word

print(seed_text)

1/1 [==============================] - 0s 21ms/step
Recurrent neural network networks are powerful


## **TASK-2**

In [ ]:
import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import SimpleRNN, Dense, Embedding
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.utils import to_categorical

In [ ]:
d = pd.read_csv("/content/hi.txt",sep=",")

In [ ]:
d

Empty DataFrame
Columns: [hi , how are you?, where are you from?, my name is vyshu, i am studing]
Index: []

In [ ]:
# Tokenizing the words
tokenizer = Tokenizer()
tokenizer.fit_on_texts(d)
total_words = len(tokenizer.word_index) + 1


In [ ]:
print(total_words)

14


In [ ]:
input_sequences = []
for word in d:
    tokenized_sentence = tokenizer.texts_to_sequences([word])[0]
    for i in range(1, len(tokenized_sentence)):
        n_gram_sequence = tokenized_sentence[:i+1]
        input_sequences.append(n_gram_sequence)


In [ ]:
print(input_sequences)

[[4, 1], [4, 1, 2], [5, 1], [5, 1, 2], [5, 1, 2, 6], [7, 8], [7, 8, 9], [7, 8, 9, 10], [11, 12], [11, 12, 13]]


In [ ]:
max_sequence_length = max([len(seq) for seq in input_sequences])
input_sequences = pad_sequences(input_sequences, maxlen=max_sequence_length, padding='pre')


In [ ]:
X, y = input_sequences[:, :-1], input_sequences[:, -1]
y = to_categorical(y, num_classes=total_words)

In [ ]:
model = Sequential()
model.add(Embedding(input_dim=total_words, output_dim=50, input_length=max_sequence_length-1))
model.add(SimpleRNN(100, return_sequences=True))
model.add(SimpleRNN(100))
model.add(Dense(total_words, activation='softmax'))


In [ ]:
# Compiling the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Training the model
model.fit(X, y, epochs=50, verbose=2)

Epoch 1/50
1/1 - 2s - loss: 2.6752 - accuracy: 0.2000 - 2s/epoch - 2s/step
Epoch 2/50
1/1 - 0s - loss: 2.5880 - accuracy: 0.2000 - 12ms/epoch - 12ms/step
Epoch 3/50
1/1 - 0s - loss: 2.5029 - accuracy: 0.3000 - 11ms/epoch - 11ms/step
Epoch 4/50
1/1 - 0s - loss: 2.4176 - accuracy: 0.5000 - 11ms/epoch - 11ms/step
Epoch 5/50
1/1 - 0s - loss: 2.3306 - accuracy: 0.6000 - 11ms/epoch - 11ms/step
Epoch 6/50
1/1 - 0s - loss: 2.2407 - accuracy: 0.6000 - 13ms/epoch - 13ms/step
Epoch 7/50
1/1 - 0s - loss: 2.1475 - accuracy: 0.6000 - 11ms/epoch - 11ms/step
Epoch 8/50
1/1 - 0s - loss: 2.0509 - accuracy: 0.6000 - 11ms/epoch - 11ms/step
Epoch 9/50
1/1 - 0s - loss: 1.9518 - accuracy: 0.6000 - 11ms/epoch - 11ms/step
Epoch 10/50
1/1 - 0s - loss: 1.8512 - accuracy: 0.6000 - 10ms/epoch - 10ms/step
Epoch 11/50
1/1 - 0s - loss: 1.7505 - accuracy: 0.6000 - 10ms/epoch - 10ms/step
Epoch 12/50
1/1 - 0s - loss: 1.6506 - accuracy: 0.6000 - 11ms/epoch - 11ms/step
Epoch 13/50
1/1 - 0s - loss: 1.5517 - accuracy: 0.600

In [ ]:
# Generating text using the trained model
seed_text = "how"
next_words = 2

for _ in range(next_words):
    tokenized_seed = tokenizer.texts_to_sequences([seed_text])[0]
    tokenized_seed = pad_sequences([tokenized_seed], maxlen=max_sequence_length-1, padding='pre')
    predicted_word_index = np.argmax(model.predict(tokenized_seed), axis=-1)
    predicted_word = tokenizer.index_word[predicted_word_index[0]]
    seed_text += " " + predicted_word

print(seed_text)

1/1 [==============================] - 0s 30ms/step
how are you
